services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - gateway_consul_data:/consul/data
    networks:
      - microservices-net
volumes:
  gateway_consul_data:
networks:
  microservices-net:
    driver: bridge
