services:
  user-service-db:
    image: 'postgres:latest'
    container_name: 'wandertrail-user-service-db'
    environment:
      - 'POSTGRES_DB=wandertrail-user-service-db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
    volumes:
      - user_service_db_data:/var/lib/postgresql
    networks:
      - microservices-net
volumes:
  user_service_db_data:
