services:
  postgres:
    image: 'postgres:latest'
    container_name: 'wandertrail-user-service-db'
    environment:
      - 'POSTGRES_DB=wandertrail-user-service-db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   environment:
  #     - 'RABBITMQ_DEFAULT_PASS=secret'
  #     - 'RABBITMQ_DEFAULT_USER=myuser'
  #   ports:
  #     - '5672'
