server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: wandertrail-user-service
  config:
    import: "optional:consul:"
  
  datasource:
    url: jdbc:postgresql://localhost:5432/wandertrail-user-service-db
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        hostname: localhost
        port: ${server.port}
        service-name: ${spring.application.name}
        health-check-url: http://host.docker.internal:${server.port}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 10s
      config:
        enabled: false
        prefixes: 
          - config 
        format: YAML
        default-context: application # This is default context use for all services user Consul config
        profile-separator: ','
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baseline-on-migrate: true # Flyway chưa chạy lần nào nhưng đã có db


management:
  endpoints:
    web:
      exposure:
        include: health, info
  # health:
  #   db:
  #     enabled: false
# Profiles (nếu muốn tách dev/prod)
# spring:
#   profiles:
#     active: dev
